name: search/kclique/5
seed: 1

log_level: info
report_interval: 10
eval_interval: 50
save_interval: 50

data_path: data/kclique
train_sets:
  - name: 5-0.2
    samples: 2000
    max_tries: 5
    max_flips: 150
    iterations: 10000

eval_set:
  name: 10-0.1
  samples: 10
  max_tries: 10
  max_flips: 300

model_path: False

gnn_hidden_size: 32
readout_hidden_size: 64

cycles: 1
optimizer: RMSprop
lr: 0.0005
lr_milestones: [200, 500, 1000, 5000]
lr_decay: 0.5

method: reinforce
discount: 0.25
walk_prob: 0.5
